### ISSUE TITLE
Consider adding a "required scopes" property in the validation/introspection middleware

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet-contrib/AspNet.Security.OAuth.Extensions#26]
With https://github.com/aspnet-contrib/AspNet.Security.OAuth.Extensions/pull/25, one will be able to use the new ASP.NET Core authorization block to create claims-based policies rejecting requests made by client applications that don't have enough privileges (= not the right scope), but I wonder if we shouldn't also provide an option allowing to configure a list of required scopes at the global level.

@DovydasNavickas @MonkeyJamboree any thoughts?

**Comment by MonkeyJamboree** [comment]
This seems similar to, but distinct from, the Audiences property, though the two seem to have very blurred lines.

I could see a use for having a required scopes option globally since there could be cases where a scope generally correlates to allowing access to a resource server, but then why wouldn't consumers just use an Audience for that? What's the distinction between a global set of scopes versus setting an Audience when all of the requested scopes are granted that are required globally for a resource server?

What other use cases might this required scopes option provide for consumers?

How does #25 tie in with this, when scopes are not necessarily claims or representative of sets of claims?

**Comment by PinpointTownes** [comment]
@MonkeyJamboree agreed. Let's keep this it in the backlog and see if someone needs it :smile:
